// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Fbp2ngLd7hIeZ-wtiawNPUIklzrDRd8',
    appId: '1:1027071617423:web:8dceb555f27901aa9703fa',
    messagingSenderId: '1027071617423',
    projectId: 'moodbrew-1498c',
    authDomain: 'moodbrew-1498c.firebaseapp.com',
    storageBucket: 'moodbrew-1498c.firebasestorage.app',
    measurementId: 'G-E61GCX8ZYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEmePCLF8zXFm1s4WQQNmR0E2HBco_SJQ',
    appId: '1:1027071617423:android:75476a9896f428159703fa',
    messagingSenderId: '1027071617423',
    projectId: 'moodbrew-1498c',
    storageBucket: 'moodbrew-1498c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0r9U-a9hd46IpXuF2upj3Xjq-cf9pNMQ',
    appId: '1:1027071617423:ios:3d088777a6a7f7e89703fa',
    messagingSenderId: '1027071617423',
    projectId: 'moodbrew-1498c',
    storageBucket: 'moodbrew-1498c.firebasestorage.app',
    iosBundleId: 'com.example.moodbrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0r9U-a9hd46IpXuF2upj3Xjq-cf9pNMQ',
    appId: '1:1027071617423:ios:3d088777a6a7f7e89703fa',
    messagingSenderId: '1027071617423',
    projectId: 'moodbrew-1498c',
    storageBucket: 'moodbrew-1498c.firebasestorage.app',
    iosBundleId: 'com.example.moodbrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Fbp2ngLd7hIeZ-wtiawNPUIklzrDRd8',
    appId: '1:1027071617423:web:a701a98f85086eb09703fa',
    messagingSenderId: '1027071617423',
    projectId: 'moodbrew-1498c',
    authDomain: 'moodbrew-1498c.firebaseapp.com',
    storageBucket: 'moodbrew-1498c.firebasestorage.app',
    measurementId: 'G-GDP5CDCDP2',
  );
}
